[package]
name = "alt_marathon"
version = "0.1.2"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
fb_poster = "0.1.8"
inline-python = "0.12.0"
regex = "1.10.4"
reqwest = "0.12.2"
serde_json = "1.0.115"
tempdir = "0.3.7"
thirtyfour = "0.31.0"
tokio = { version = "1.37.0", features = ["full"] }